version: '3'

services:
  eureka-server:
    image: dinomov/eureka-server:latest
    ports:
      - "8761:8761" 

  stock-service:
    image: dinomov/stock-service:latest
    command: dockerize -wait http://localhost::8761 -timeout 30s java -jar /app/stock-service.jar
    depends_on:
      - eureka-server
    ports:
      - "8088:8088" 

  product-service:
    image: dinomov/product-service:latest
    command: dockerize -wait http://localhost::8761 -timeout 30s java -jar /app/product-service.jar
    depends_on:
      - eureka-server
    ports:
      - "8087:8087"  

  