spring:
  application:
    name: StockService
  config:
    activate:
      on-profile: instance2

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/